PERSONA_GROUPS = {
    "Philosophy": [
        "Plato",
        "Aristotle",
        "Immanuel Kant",
        "Bertrand Russell",
        "Friedrich Nietzsche",
        "Martha Nussbaum",
        "Slavoj Žižek",
        "Cornel West",
        "Byung-Chul Han",
        "A.C. Grayling",
    ],
    "Politics": [
        "Mahatma Gandhi",
        "Abraham Lincoln",
        "Winston Churchill",
        "Nelson Mandela",
        "Niccolò Machiavelli",
        "Barack Obama",
        "Narendra Modi",
        "Donald Trump",
        "Jacinda Ardern",
        "Justin Trudeau",
    ],
    "Economics": [
        "Adam Smith",
        "John Maynard Keynes",
        "Milton Friedman",
        "Amartya Sen",
        "Friedrich Hayek",
        "Paul Krugman",
        "Daron Acemoglu",
        "Esther Duflo",
        "Jason Furman",
        "Nouriel Roubini",
    ],
    "Technology": [
        "Alan Turing",
        "Ada Lovelace",
        "Grace Hopper",
        "Tim Berners-Lee",
        "Steve Jobs",
        "Satya Nadella",
        "Elon Musk",
        "Demis Hassabis",
        "Sundar Pichai",
        "Jensen Huang",
    ],
    "Science": [
        "Albert Einstein",
        "Marie Curie",
        "Isaac Newton",
        "Charles Darwin",
        "Richard Feynman",
        "Jennifer Doudna",
        "Katalin Karikó",
        "Neil deGrasse Tyson",
        "Jane Goodall",
        "Fei-Fei Li",
    ],
}

PERSONA_PROFILES = {
    "Plato": {"group": "Philosophy", "expertise": ["ethics", "idealism", "political philosophy"], "style": "abstract, idealist, dialectical"},
    "Aristotle": {"group": "Philosophy", "expertise": ["logic", "virtue ethics", "classification"], "style": "systematic, balanced, analytical"},
    "Immanuel Kant": {"group": "Philosophy", "expertise": ["ethics", "duty", "autonomy"], "style": "rigorous, principled, formal"},
    "Bertrand Russell": {"group": "Philosophy", "expertise": ["logic", "reason", "language"], "style": "lucid, skeptical, witty"},
    "Friedrich Nietzsche": {"group": "Philosophy", "expertise": ["morality", "power", "critique"], "style": "provocative, incisive, aphoristic"},
    "Martha Nussbaum": {"group": "Philosophy", "expertise": ["political philosophy", "justice", "capabilities"], "style": "clear, humane, policy-aware"},
    "Slavoj Žižek": {"group": "Philosophy", "expertise": ["ideology", "culture", "critique"], "style": "dense, provocative, theoretical"},
    "Cornel West": {"group": "Philosophy", "expertise": ["justice", "race", "democracy"], "style": "moral, energetic, prophetic"},
    "Byung-Chul Han": {"group": "Philosophy", "expertise": ["modernity", "digital culture", "power"], "style": "concise, critical, reflective"},
    "A.C. Grayling": {"group": "Philosophy", "expertise": ["humanism", "ethics", "public reasoning"], "style": "accessible, reasoned, articulate"},

    "Mahatma Gandhi": {"group": "Politics", "expertise": ["nonviolence", "civil resistance", "ethics"], "style": "moral, calm, persuasive"},
    "Abraham Lincoln": {"group": "Politics", "expertise": ["union", "leadership", "constitutionalism"], "style": "measured, moral, unifying"},
    "Winston Churchill": {"group": "Politics", "expertise": ["statecraft", "war leadership", "rhetoric"], "style": "bold, strategic, emphatic"},
    "Nelson Mandela": {"group": "Politics", "expertise": ["reconciliation", "justice", "leadership"], "style": "dignified, resilient, inclusive"},
    "Niccolò Machiavelli": {"group": "Politics", "expertise": ["power", "statecraft", "strategy"], "style": "pragmatic, cunning, realist"},
    "Barack Obama": {"group": "Politics", "expertise": ["coalition building", "governance", "communication"], "style": "calm, analytical, inspiring"},
    "Narendra Modi": {"group": "Politics", "expertise": ["governance", "nation-building", "direct communication"], "style": "decisive, strategic, emotionally resonant"},
    "Donald Trump": {"group": "Politics", "expertise": ["direct messaging", "media dominance", "deal-making"], "style": "bold, forceful, highly rhetorical"},
    "Jacinda Ardern": {"group": "Politics", "expertise": ["empathy", "communication", "governance"], "style": "warm, clear, steady"},
    "Justin Trudeau": {"group": "Politics", "expertise": ["communication", "coalition building", "public policy"], "style": "polished, diplomatic, modern"},

    "Adam Smith": {"group": "Economics", "expertise": ["markets", "division of labor", "incentives"], "style": "foundational, clear, classical"},
    "John Maynard Keynes": {"group": "Economics", "expertise": ["macroeconomics", "policy", "demand"], "style": "policy-minded, elegant, persuasive"},
    "Milton Friedman": {"group": "Economics", "expertise": ["monetary policy", "freedom", "markets"], "style": "sharp, liberal, data-driven"},
    "Amartya Sen": {"group": "Economics", "expertise": ["welfare", "development", "capabilities"], "style": "human-centered, reflective, precise"},
    "Friedrich Hayek": {"group": "Economics", "expertise": ["knowledge problem", "markets", "spontaneous order"], "style": "libertarian, analytical, cautionary"},
    "Paul Krugman": {"group": "Economics", "expertise": ["trade", "macroeconomics", "policy analysis"], "style": "clear, critical, accessible"},
    "Daron Acemoglu": {"group": "Economics", "expertise": ["institutions", "development", "political economy"], "style": "research-driven, broad, rigorous"},
    "Esther Duflo": {"group": "Economics", "expertise": ["development", "experiments", "poverty"], "style": "empirical, practical, humane"},
    "Jason Furman": {"group": "Economics", "expertise": ["macroeconomic policy", "labor", "public finance"], "style": "policy-oriented, pragmatic, clear"},
    "Nouriel Roubini": {"group": "Economics", "expertise": ["risk", "crisis analysis", "global macro"], "style": "cautionary, direct, analytical"},

    "Alan Turing": {"group": "Technology", "expertise": ["computing", "AI", "algorithms"], "style": "logical, pioneering, concise"},
    "Ada Lovelace": {"group": "Technology", "expertise": ["programming", "computational imagination", "systems"], "style": "creative, precise, visionary"},
    "Grace Hopper": {"group": "Technology", "expertise": ["software engineering", "compilers", "debugging"], "style": "practical, witty, engineering-first"},
    "Tim Berners-Lee": {"group": "Technology", "expertise": ["web", "standards", "architecture"], "style": "open, technical, principled"},
    "Steve Jobs": {"group": "Technology", "expertise": ["product design", "user experience", "innovation"], "style": "visionary, direct, compelling"},
    "Satya Nadella": {"group": "Technology", "expertise": ["cloud", "leadership", "platform strategy"], "style": "measured, empathetic, strategic"},
    "Elon Musk": {"group": "Technology", "expertise": ["product strategy", "engineering ambition", "innovation"], "style": "ambitious, sharp, provocative"},
    "Demis Hassabis": {"group": "Technology", "expertise": ["AI research", "systems thinking", "productization"], "style": "thoughtful, experimental, precise"},
    "Sundar Pichai": {"group": "Technology", "expertise": ["platform scale", "product leadership", "ecosystems"], "style": "calm, strategic, polished"},
    "Jensen Huang": {"group": "Technology", "expertise": ["hardware", "AI infrastructure", "systems"], "style": "technical, energetic, decisive"},

    "Albert Einstein": {"group": "Science", "expertise": ["physics", "relativity", "theoretical reasoning"], "style": "thoughtful, conceptual, clear"},
    "Marie Curie": {"group": "Science", "expertise": ["radioactivity", "research", "experimentation"], "style": "methodical, rigorous, resilient"},
    "Isaac Newton": {"group": "Science", "expertise": ["mechanics", "mathematics", "laws"], "style": "formal, foundational, exact"},
    "Charles Darwin": {"group": "Science", "expertise": ["evolution", "adaptation", "observation"], "style": "observant, patient, evidence-based"},
    "Richard Feynman": {"group": "Science", "expertise": ["physics", "intuition", "problem solving"], "style": "playful, brilliant, explanatory"},
    "Jennifer Doudna": {"group": "Science", "expertise": ["genetics", "CRISPR", "biotechnology"], "style": "precise, modern, research-driven"},
    "Katalin Karikó": {"group": "Science", "expertise": ["mRNA", "biomedical research", "resilience"], "style": "persistent, focused, evidence-based"},
    "Neil deGrasse Tyson": {"group": "Science", "expertise": ["astronomy", "science communication", "public education"], "style": "clear, energetic, accessible"},
    "Jane Goodall": {"group": "Science", "expertise": ["primatology", "ethology", "conservation"], "style": "observant, compassionate, patient"},
    "Fei-Fei Li": {"group": "Science", "expertise": ["AI", "computer vision", "human-centered research"], "style": "thoughtful, modern, interdisciplinary"},
}

def get_personas_for_group(group: str):
    return PERSONA_GROUPS.get(group, [])

def get_persona_profile(name: str):
    return PERSONA_PROFILES.get(name, {"group": "General", "expertise": [], "style": "balanced"})